name: lint check
on: 
  push:
    paths:
      - src/pages/*

jobs:
  eslint:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get yarn chache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with: 
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{　runner.os　}}-yarn-${{　hashFiles("**/yarn.lock") }}
          restore-keys: |
            ${{runner.os}}-yarn-
      - name: install package
        run: yarn
      - name: run eslint
        run: yarn lint
      